# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-${{ matrix.app.name }}    # ensure only one deploy per app at a time
    strategy:
      matrix:
        app:
          - name: backend
            config: deploy/fly.backend.toml
          - name: web
            config: deploy/fly.web.toml
          - name: bot
            config: deploy/fly.bot.toml
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only -c ${{ matrix.app.config }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
